services:
  ledger:
    build: .
    volumes:
      - ./ledger:/app/ledger
      - ./scripts:/app/scripts
      - ./output:/app/output  # 出力ファイル用ディレクトリ
    working_dir: /app
    ports:
      - "5000:5000"  # hledger-web 用のポート
